import Link from 'next/link';
import { useState } from 'react';
import { useRouter } from 'next/router';
import { Flex, Box, Text, Input, InputGroup, InputRightElement, Button, rightIcon, useToast, Spinner } from "@chakra-ui/react";
import { ViewIcon, ViewOffIcon, ArrowForwardIcon } from '@chakra-ui/icons';
import Head from 'next/head';
import google from '../assets/google.png';
import github from '../assets/github.png';
import logo from '../assets/logo.png';
import Image from 'next/image';

export default function Home() {
    const router = useRouter();
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [load, setLoad] = useState(false);
    const toast = useToast();
    const [show, setShow] = useState(false);
    const handleClick = () => setShow(!show);
    const [error, setError] = useState('');
    function handleChange(e) {
        if (e.target.name === "email") {
            setEmail(e.target.value);
        } else if (e.target.name === "password") {
            setPassword(e.target.value);
        }
    }

    async function handleSubmit(e) {
        e.preventDefault();
        const data = { email, password };
        if (email.length && password.length) {
            setLoad(true);
            let res = await fetch(`http://localhost:3000/api/login`, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                },
                body: JSON.stringify(data),
            });
            if (res.ok) {
                let response = await res.json();
                console.log(response.token);
                let auth = await fetch(`http://localhost:3000/api/auth`, {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json",
                        "Bearer": response.token
                    }
                });
                let authData = await auth.json();
                console.log(authData.data[0].id);
                const key = authData.data[0].id;
                localStorage.setItem('key', key);
                setLoad(false);
                router.push('/Home');
            }
            else {
                setError(res.statusText);
                setLoad(false);
            }
        }
    }
    return (
        <>
            <Head>
                <title>DSA 375</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box bg="brand.900" minH="100vh" color="white" fontFamily="body.1">
                <Flex justifyContent="space-between" px="4rem" py="2rem">
                    <Flex alignItems="center"><Image src={logo} style={{ filter: 'invert(1)', height: '2rem', width: '3rem', marginRight: '2rem' }} /><Text fontSize="1.5rem" fontWeight="700">DSA Prep</Text></Flex>
                    <Link href="/Signup"><h1>Sign up</h1></Link>
                </Flex>
                <Flex justifyContent="center" alignItems="center" flexDirection="column">
                    <Text fontWeight={800} fontSize="2.5rem" my="0.75rem">Login to Your Account</Text>
                    {!error.length && <Text color="#8d8d8d" textAlign="center" w="50rem" fontSize="1rem">Welcome Back Coder! Login to your account and resume your DSA progress</Text>}
                    {error.length > 0 && <Text color="#dc143c">{error + '!'}</Text>
                    }
                </Flex>
                <Flex justifyContent="center" mt="5rem" mb="2rem">
                    <Flex flexDirection="column" w="25rem">
                        <form onSubmit={handleSubmit}>
                            <Input placeholder='Email ID' variant='unstyled' py="1rem" px="1.5rem" bg="#222222" type="email" my="0.5rem" value={email} onChange={handleChange} name="email" />
                            <InputGroup py="1rem" px="1.5rem" bg="#222222" my="0.5rem" borderRadius="5px" display="flex" alignItems="center">
                                <Input
                                    pr='4.5rem'
                                    type={show ? 'text' : 'password'}
                                    placeholder='Password'
                                    variant='unstyled'
                                    value={password} onChange={handleChange}
                                    name="password"
                                />
                                <InputRightElement width='4.5rem' h="100%">
                                    <Button _hover={{ bg: "none" }} p="0" h="0" minW="0" bg="none" onClick={handleClick}>
                                        {show ? <ViewOffIcon /> : <ViewIcon />}
                                    </Button>
                                </InputRightElement>
                            </InputGroup>
                            <Button rightIcon={load ? <Spinner /> : <ArrowForwardIcon />} bg="linear-gradient(90deg, #715AE3 0%, #AC82C8 100%)" _hover={{ bg: "linear-gradient(90deg, #AC82C8 0%, #715AE3 100%)" }} transition="all 0.5s ease-in-out" py="1rem" px="1.5rem" fontSize="1rem" justifyContent="space-between" h="55px" my="0.5rem" type="submit" w="100%" >Login to Your Account</Button>
                        </form>
                    </Flex>
                    <Flex justifyContent="center" alignItems="center" px="8rem">
                        <Text fontWeight="800">/</Text>
                    </Flex>
                    <Flex flexDirection="column" w="25rem" justifyContent="center">
                        <Box bg="linear-gradient(90deg, #715AE3 0%, #AC82C8 100%)" p="0.15rem" borderRadius="7px" h="55px" my="0.5rem"><Button h="100%" w="100%" bg="brand.900" _hover={{ bg: "white", color: "black" }} ><Image src={google} style={{height: '1.5rem', width: '1.5rem', marginRight: '1rem'}}/>Sign in with Google</Button></Box>
                        <Box bg="linear-gradient(90deg, #715AE3 0%, #AC82C8 100%)" p="0.15rem" borderRadius="7px" h="55px" my="0.5rem"><Button h="100%" w="100%" bg="brand.900" _hover={{ bg: "white", color: "black" }}><Image src={github} style={{height: '1.5rem', width: '1.5rem', marginRight: '1rem'}}/>Sign in with Github</Button></Box>
                    </Flex>
                </Flex>
                <Flex justifyContent="space-between" px="2rem" py="2rem" fontSize="0.75rem" color="#8d8d8d" position="fixed" bottom="0" left="0" w="100%">
                    <a href='https://github.com/Manish-XD/dsa-prep' target='_blank'>Github</a>
                    <Text>Copyright&copy;DSA prep 2023</Text>
                </Flex>
            </Box>
        </>
    )
}
