import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Sidebar from '../components/sidebar';
import Footer from '../components/footer';
import Link from 'next/link';

export default function Home({data}) {
  // console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar/>
      <main className={styles.main}>
        <h1>&#123; &#125; 375 Data structure and algorithms Practice Questions.</h1>
        <p>Data structure and algorithms help in understanding the nature of the problem at a deeper level and thereby a better understanding of the world.</p>
        {
         data.map((item)=>{
          return <div key={item.topic} >
            <h1>{item.topic}</h1>
            <Link href={`/topic/${item.topic}`}>{item.topic}</Link>
          </div>
         })
        }
      </main>
      <Footer/>
    </div>
  )
}

export async function getServerSideProps(context) {
  // const url = "https://dsapppi.herokuapp.com/Arrays";
  // let data = await fetch(url);
  // fetch(url).then(res => res.json()).then(data => console.log(data.links[0].link))
  const res = await fetch(`https://dsapppi.herokuapp.com`);
  const data = await res.json();
  return {
    props: {data}, // will be passed to the page component as props
  }
}
